version: 1.BETA.{build}
# skip_tags is important or you will get an infinite build loop when we apply release tags
# testing itzabird appveyor
skip_tags: true
skip_branch_with_pr: true

cache:
- _build\

environment:
  svn_url: https://svn.code.sf.net/p/stones2stars/code/trunk
  release_prefix: Stones2Stars
  build_dir: _build
  release_branch: release
  svn_user: s2sappveyour
  svn_pass:
    secure: T8MivnrThpqDptrSafu2kWSvadsSCOtu9KkamwqNm20=
  WEBHOOK_URL:
    secure: 6hg1/q82Oatu+Swl6MRrqf81pFqjPTwPSfIDwzoERyCfYbjWeE+xm6NObTx+8MwGGxDmvpYKs0olhCbgp5txi4eBO/Er5o7eHydLganoCvIld/bPMP8LrzIMKoEZOGfryI5D0/qSBFdgmyzVrmaX7PVkRzYZJQUSQLUucJXUHls=
  # git_email:
  #   secure: trN7d/FWgBATcyR/BWbF313Avez3hsRfOq4PdxNcll0=
  # git_user: flabbert
  # git_access_token:
  #   secure: /wUaPN2WiulxpYjI5oJzoadfI+BY6w9toeIK20J2kob7116rdXEj7FrXrNU4SwnhyELyIrwEOnWS/cxkFMQOoZYKsVqcZt/8TD62Px1rOpXewA7wN2ZPT5zm+9Io2c+O

build_script:
  - cmd: >-
      call Powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%APPVEYOR_BUILD_FOLDER%\Tools\CI\fix_sources_timestamps.ps1"

      call "%APPVEYOR_BUILD_FOLDER%\Tools\_AppveyorTestBuild.bat"

test_script:
  - cmd: >-
      cd Tools

      XmlValidator.exe -a

deploy_script:
  - cmd: >-
      call "%APPVEYOR_BUILD_FOLDER%\Tools\CI\DeployBuild.bat"

      call "%APPVEYOR_BUILD_FOLDER%\Tools\_TrimFBuildCache.bat"

on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEBHOOK_URL
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL